# Generated by Django 3.0.5 on 2020-11-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='employee/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=12)),
                ('first_address', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=122)),
                ('country', models.CharField(max_length=122)),
                ('pincode', models.IntegerField(default=0)),
            ],
        ),
    ]
